---
- name: Ensure reverse proxy on the edge server
  hosts: public
  become: true
  roles:
    - role: maxhoesel.caddy.caddy_server
      become: true
      tags: [caddy]
      vars:
        caddy_apply_config: true
        caddy_config_mode: Caddyfile
        caddy_caddyfile: "{{ lookup('template', proxy_caddy_template_path) }}"

    - role: haproxy
      become: true
      tags: [haproxy]
      vars:
        haproxy_config_template_src: "{{ proxy_haproxy_template_path }}"