---
- name: Check if service vault exists
  ansible.builtin.stat:
    path: "{{ _svc.path }}/{{ _manifest.vault_file }}"
  register: _svc_vault_file
  when: _manifest.vault_file is defined

- name: Load service-specific vault variables
  ansible.builtin.include_vars:
    file: "{{ _svc.path }}/{{ _manifest.vault_file }}"
    name: _vault
  when:
    - _manifest.vault_file is defined
    - _svc_vault_file.stat.exists | default(false)

# jinja2 template to loop over the vault and resolve the secret variables in manifest to achieve variable indirection
- name: Resolve manifest secrets from vault
  ansible.builtin.set_fact:
    _secrets: >-
      {%- set resolved = {} -%}
      {%- for k, v in _manifest.secrets.items() -%}
      {%-   set _ = resolved.update({k: _vault[v]}) -%}
      {%- endfor -%}
      {{ resolved }}
  when: _manifest.secrets is defined
