pub_ssh_key_ansible: "{{ vault_pub_ssh_key_ansible }}"
ssh_key_ansible: "{{ vault_ssh_key_ansible }}"

azure_client_id: "{{ vault_azure_client_id }}"
azure_client_secret: "{{ vault_azure_client_secret }}"
azure_tenant_id: "{{ vault_azure_tenant_id }}"
azure_subscription_id: "{{ vault_azure_subscription_id }}"

tailscale_oauth_key: "{{ vault_tailscale_oauth_key }}"

base_domain: "{{ vault_base_domain }}"

bella: 100.96.156.117
rubie: 100.107.240.67
teddy: 100.80.19.125
raj: 100.98.110.23