# vim: ft=make

set ignore-comments := true
set shell := ["bash", "-c"]
with-env := "export $(sops -d env.enc.yaml | yq -r 'to_entries | .[] | .key + \"=\" + .value') &&"

default:
    @just --list

switch_workspace env:
    @if [ -z "$TF_WORKSPACE" ]; then {{with-env}} terraform workspace select {{env}} -no-color 2>/dev/null || terraform workspace new {{env}} -no-color; else echo "TF_WORKSPACE is set to $TF_WORKSPACE, skipping workspace switch"; fi

init :
    @{{with-env}} TF_LOG=ERROR terraform init -no-color > /dev/null && echo "Terraform init was successfull"

validate: init
    @terraform fmt -check -recursive -list=true -diff
    @terraform validate -no-color

fmt:
	@terraform fmt -recursive -list=true -diff

plan env="staging": init 
	@just decrypt {{env}}
	@just switch_workspace {{env}}
	@{{with-env}} terraform plan -out=tfplan-{{env}} -var-file={{env}}.tfvars.json -no-color

apply env *flags: init 
	@just switch_workspace {{env}}
	@{{with-env}} terraform apply {{flags}} tfplan-{{env}}
	
update-env:
	@sops -e env.yaml > env.enc.yaml

encrypt env="staging":
	@sops -e  {{env}}.tfvars.json > {{env}}.tfvars.enc.json

decrypt env="staging":
	@sops -d {{env}}.tfvars.enc.json > {{env}}.tfvars.json

unlock lock-id:
	@{{with-env}} terraform force-unlock {{lock-id}}
	
edit file:
    @sops edit {{file}}