services:
  webdav:
    image: hacdias/webdav:v5
    container_name: webdav
    restart: unless-stopped
    environment:
      - WD_CONFIG=/etc/webdav/config.yaml
      - WD_PORT=80
    volumes:
      - ./config.yaml:/etc/webdav/config.yaml
      - ./notes:/data
    ports:
      - "9876:80"
  filestash:
    image: machines/filestash:latest
    container_name: filestash
    restart: unless-stopped
    ports:
      - "8334:8334"
    volumes:
      - filestash_data:/app/data/state/

volumes:
  filestash_data:
