name: "Terraform Setup"
description: "Setup Terraform, Azure Login, and Just"
inputs:
  terraform_version:
    required: true
    default: "1.15.8"
  age-private-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Official Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: true

    - name: Detect Architecture and Install Tools
      shell: bash
      run: |
        # Detect Arch (maps 'aarch64' to 'arm64' and 'x86_64' to 'amd64')
        ARCH=$(uname -m)
        if [ "$ARCH" = "aarch64" ]; then TARGET="arm64"; else TARGET="amd64"; fi
        echo "Detected architecture: $TARGET"
        echo "ARCH=$TARGET" >> $GITHUB_ENV

        sudo apt-get update
        sudo apt-get install -y just unzip curl

    - name: Install SOPS
      shell: bash
      run: |
        curl -LO "https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.${{ env.ARCH }}"
        sudo mv sops-v3.9.4.linux.${{ env.ARCH }} /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops

    - name: Install age
      shell: bash
      run: |
        curl -LO "https://github.com/FiloSottile/age/releases/download/v1.2.1/age-v1.2.1-linux-${{ env.ARCH }}.tar.gz"
        tar -xzf age-v1.2.1-linux-${{ env.ARCH }}.tar.gz
        sudo mv age/age /usr/local/bin/
        sudo mv age/age-keygen /usr/local/bin/
        rm -rf age age-v1.2.1-linux-${{ env.ARCH }}.tar.gz

    - name: Export SOPS Key
      shell: bash
      run: echo "SOPS_AGE_KEY=${{ inputs.age-private-key }}" >> $GITHUB_ENV

    - name: Install Azure CLI
      shell: bash
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
