apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fah-data-pvc
  namespace: stress
  labels:
    app: foldingathome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bella-storage-class
  resources:
    requests:
      storage: 1.5Gi
  selector:
    matchLabels:
      app: foldingathome
