apiVersion: v1
kind: Service
metadata:
  name: foldingathome
  namespace: stress
  labels:
    app: foldingathome
spec:
  selector:
    app: foldingathome
  ports:
    - port: 7396
      targetPort: 7396
  type: ClusterIP
