apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-march
  namespace: apps
  labels:
    app: portfolio-march
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-march
  template:
    metadata:
      labels:
        app: portfolio-march
    spec:
      containers:
        - name: portfolio-karma
          image: adiqtpi/portfolio_march:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.50"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
