apiVersion: v1
kind: Service
metadata:
  name: portfolio-march
  namespace: apps
  labels:
    app: portfolio-march
spec:
  selector:
    app: portfolio-march
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
